name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run shellcheck and shfmt on ./script.sh
        run: |
          sudo apt-get -qq install shellcheck -y > /dev/null
          shellcheck --version
          sudo apt-get -qq install shfmt -y > /dev/null
          shfmt --version
          shellcheck ./script.sh
          shfmt -i 4 -d ./script.sh
