name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run shellcheck and shfmt on ./script.sh
        run: |
          sudo apt install shellcheck shfmt -y
          shellcheck ./script.sh
          shfmt -i 8 -d ./script.sh
