name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck on ./script.sh
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install shellcheck -y
          shellcheck --version
          shellcheck ./script.sh
